databases:
  - name: postgres
    databaseName: employees
    user: admin

services:
  - type: web
    name: employeesCRUD
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn employeesCRUD.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4