# Generated by Django 4.2 on 2023-04-08 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_empleado_codigo_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('codigo', models.SmallIntegerField(default=0, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('presupuesto', models.BigIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='id',
        ),
        migrations.AddField(
            model_name='empleado',
            name='apellido1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='empleado',
            name='appellido2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='empleado',
            name='codigo',
            field=models.SmallIntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='empleado',
            name='nif',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AddField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='empleado',
            name='codigo_departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.departamento'),
        ),
    ]
