# Generated by Django 4.2 on 2023-04-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_empleado_codigo_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='presupuesto',
            field=models.BigIntegerField(default=0),
        ),
    ]
