POST http://localhost:1234/api/empleados/crear  HTTP/1.1
content-type: application/json

{
    "codigo": 2143,
    "nif": 430,
    "nombre": "richi",
    "apellido1": "rafi",
    "apellido2": "qk",
    "codigo_departamento": 5128
}