# Generated by Django 4.2 on 2023-04-07 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='codigo_departamento',
        ),
    ]
