# Generated by Django 4.2 on 2023-04-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_departamento_remove_empleado_id_empleado_apellido1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
    ]
