# Generated by Django 4.2 on 2023-04-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_departamento_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='codigo',
            field=models.SmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
