# Generated by Django 4.2 on 2023-04-11 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_empleado_codigo_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='codigo_departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.departamento'),
        ),
    ]
